apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels: ##variavel
        app: apache
    spec:
      containers:
      - name: apache
        image: {{ .Values.api.image }}
        ports:
        - containerPort: 8000
        
    


