apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
  selector: 
    app: {{ .Release.Name }}
  type: {{ .Values.api.service.type}}

  ##N3bZec9KN-mx9bg7