apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 8000
      targetPort: 8000
  selector: 
    app: {{ .Release.Name }}