apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  # Porta para NGINX
    - name: nginx
      port: 8080
      targetPort: 8080
  # Porta para a aplicação
    - name: app
      port: 8000
      targetPort: 8000
  type: {{ .Values.api.service.type}}

  ##N3bZec9KN-mx9bg7